
CATEGORIES =  [
      "Electronics",
      "Audio",
      "Home Appliances",
      "Furniture",
      "Office Supplies",
      "Computers",
      "Gaming",
      "Kitchen Appliances",
      "Coffee",
      "Accessories",
      "Mobile Phones",
      "Cooking",
      "Sports",
      "Fitness",
      "Tools",
      "Home Improvement",
      "Health",
      "Personal Care",
      "Transport",
      "Recreation",
      "Energy Saving",
      "Bedding",
      "Home",
      "Technology",
      "Lighting",
      "Outdoor",
      "Water Sports",
      "Home Security",
      "Kids",
      "Cooling",
      "Networking",
      "Heating",
      "Grooming",
      "Toys"
    ]

FEATURES =  [
      "Noise Cancelling",
      "Bluetooth 5.0",
      "Over-Ear",
      "4K UHD",
      "HDR10",
      "Smart TV",
      "Adjustable",
      "Mesh Back",
      "Lumbar Support",
      "Intel i7",
      "RTX 3060",
      "144Hz Display",
      "Automatic",
      "15-bar Pressure",
      "Milk Frother",
      "USB-C",
      "Fast Charging",
      "Compact",
      "Wireless",
      "Adjustable DPI",
      "Silent Clicks",
      "5G",
      "108MP Camera",
      "AMOLED Display",
      "Automatic Shut-Off",
      "Boil-Dry Protection",
      "Non-Slip",
      "Eco-Friendly",
      "6mm Thick",
      "Cordless",
      "18V",
      "20 Accessories",
      "HEPA Filter",
      "3 Fan Speeds",
      "Timer",
      "Foldable",
      "20-Mile Range",
      "LED Headlight",
      "7-in-1",
      "6-Quart Capacity",
      "Stainless Steel",
      "Wi-Fi",
      "Voice Control",
      "Self-Charging",
      "Rechargeable",
      "5 Cleaning Modes",
      "2-Minute Timer",
      "App Control",
      "Energy Saving",
      "Adjustable Weight",
      "5-50 lbs",
      "Non-Slip Grip",
      "Lightweight",
      "40-Minute Runtime",
      "Solar Powered",
      "Waterproof",
      "8-Pack",
      "Adjustable Temperature",
      "Compact Size",
      "Non-Stick Basket",
      "1080p",
      "Night Vision",
      "Motion Detection",
      "Height Adjustable",
      "Electric Motor",
      "Memory Preset",
      "Variable Speed",
      "Stainless Steel Blades",
      "64-Ounce Container",
      "15 lbs",
      "Breathable",
      "Machine Washable",
      "2000 PSI",
      "Electric",
      "Quick-Connect Nozzles",
      "Adjustable Resistance",
      "LCD Display",
      "Bottle Holder",
      "Large Print Area",
      "Multi-Filament Support",
      "DIY Assembly",
      "Rotisserie",
      "Dehydrator",
      "Digital Display",
      "Color Changing",
      "Two-Way Audio",
      "Ventilation Windows",
      "Easy Setup",
      "Temperature Control",
      "Instant Hot Water",
      "2.5L Capacity",
      "Air Compression",
      "Heat",
      "Portable",
      "3-Piece Set",
      "High-Density",
      "Subwoofer",
      "Remote Control",
      "Ergonomic",
      "Reversible Blades",
      "5 Fans",
      "RGB Lights",
      "Adjustable Stand",
      "Dual-Band",
      "Parental Controls",
      "App Management",
      "Indicator Light",
      "Thermostat",
      "Two-Person",
      "Includes Oars",
      "Hand Pump",
      "Compact Design",
      "LED Light",
      "Precision Blades",
      "Multiple Combs",
      "High Accuracy",
      "Step-On Technology",
      "Tempered Glass",
      "Voice Commands",
      "Programmable",
      "Interactive",
      "Glass Lid",
      "USB Powered",
      "3 Speeds",
      "Adjustable Angle"
    ]
COLORS = [
      "Black",
      "White",
      "Gray",
      "Silver",
      "Blue",
      "Red",
      "Yellow",
      "Purple",
      "Green",
      "Multi-color",
      "Pink",
      "Brown"
    ]

MANUFACTURERS = [
      "SoundCo",
      "VisionTech",
      "ComfortSeating",
      "GameMaster",
      "CaféBrew",
      "ChargeMaster",
      "TechGear",
      "PhoneX",
      "HomeComfort",
      "FitFlex",
      "ToolMax",
      "PureAir",
      "EcoRide",
      "CookMaster",
      "CleanBot",
      "BrightSmile",
      "EcoTemp",
      "FitHome",
      "VacMaster",
      "SunGlow",
      "HealthyFry",
      "SafeHome",
      "WorkWell",
      "BlendPro",
      "RestWell",
      "CleanPro",
      "RideFit",
      "PrintMaster",
      "CookSmart",
      "BrightHome",
      "RideKids",
      "SafeView",
      "CampersWay",
      "HotServe",
      "RelaxCo",
      "FitRelief",
      "SoundMax",
      "DeskCo",
      "BreezeHome",
      "CoolTech",
      "NetMax",
      "WaffleKing",
      "HeatPro",
      "AquaSports",
      "ToolEase",
      "TrimPro",
      "WeightWise",
      "RoboFun",
      "SkilletMaster",
      "CoolBreeze"
    ]

  
  