PLOT_VECTOR_DIMENSION = 384  # Dimension of the embedding vector (for 'all-MiniLM-L6-v2' model)
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0
LEARNING_RATE = 0.5
NUM_RECO = 20
SIMILAR_USER_VECTOR_DISTANCE_THRESHOLD = 0.3
SIMILAR_MOVIE_VECTOR_DISTANCE_THRESHOLD = 0.3
CONTENT_BASED_RECO_COUNT = 5
from config.movie_config import GENERES, ACTOR_CLUSTERS
from config.categories_config import CATEGORIES, FEATURES, COLORS, MANUFACTURERS

GENRE_VECTOR_DIMENSION = len(GENERES)  
ACTOR_CLUSTERS_VECTOR_DIMENSION = len(ACTOR_CLUSTERS)
YEAR_VECTOR_DIMENSION = 1

MOVIE_PROFILE_VECTOR_DIMENSION = PLOT_VECTOR_DIMENSION + GENRE_VECTOR_DIMENSION + ACTOR_CLUSTERS_VECTOR_DIMENSION + YEAR_VECTOR_DIMENSION


TEXT_EMBEDDING_SIZE = 384
PRODUCT_PROFILE_VECTOR_DIMENSION = 300


CATEGORIES_VECTOR_DIMENSION = len(CATEGORIES)
FEATURES_VECTOR_DIMENSION = len(FEATURES)
COLORS_VECTOR_DIMENSION = len(COLORS)
MANUFACTURER_VECTOR_DIMENSION = len(MANUFACTURERS)
NUMERICAL_VECTOR_DIMENSION= 5 # we have 5 numerical features
PRODUCT_PROFILE_VECTOR_DIMENSION= 2 * TEXT_EMBEDDING_SIZE + \
                                CATEGORIES_VECTOR_DIMENSION + FEATURES_VECTOR_DIMENSION + \
                                COLORS_VECTOR_DIMENSION + MANUFACTURER_VECTOR_DIMENSION+ \
                                NUMERICAL_VECTOR_DIMENSION # 2 text embeddings along with catgorical embeddings and numerical embeddings

MOVIEDATA_FILEPATH= 'data/cleaned_movies_data.json'
PRODUCTS_DATA_FILEPATH = 'data/products/products.json'